### ISSUE TITLE
Getting "fatal" result 

### ISSUE THREAD

**Issue by nikitasinelnikov** [iamdharmesh/action-wordpress-pot-generator#3]
Hi, thanks for your useful action for *.pot files generation!

I tried to use your action yesterday to generate a pot file for a plugin. I applied the same settings as before for the previous plugin. But the file after generation is not written to my repository. Is this something on your side or should I change the launch of the action in my yml file?

There are the logs for the previous using (2022-02-07) and yesterday (22-04-17) 
[log 2022-04-17.txt](https://github.com/iamdharmesh/action-wordpress-pot-generator/files/8504618/log.2022-04-17.txt)
[log 2022-02-07.txt](https://github.com/iamdharmesh/action-wordpress-pot-generator/files/8504619/log.2022-02-07.txt)

Best Regards!

**Comment by odil-io** [comment]
I'm also getting the same error on a clean repo after following the instructions in README.md.

> fatal: unsafe repository ('/github/workspace' is owned by someone else)

**Comment by iamdharmesh** [comment]
Hi @nikitasinelnikov @odil-io, 

Thanks for reporting the issue, it seems @odil-io already figured out the issue and fix for the same. I will review the PR soon.

Best Regards!!

**Comment by iamdharmesh** [comment]
Fixed in v1.0.4
@odil-io Thanks a lot for the quick fix this.

**Comment by nikitasinelnikov** [comment]
Hi @odil-io and @iamdharmesh 

Thank you guys for the quick fix.

But I have another issue:
https://www.screencast.com/t/uZJnY3VAN5Fc

I don't know why it's the wrong URL because it's the proper repo's URL https://github.com/ultimatemember/recaptcha

YML file is here: https://github.com/ultimatemember/recaptcha/blob/master/.github/workflows/translations.yml
Secure token exists: https://www.screencast.com/t/b0gjAzPLxtRO

Let me know if you have thoughts or ideas on how to fix that,
Best Regards!

**Comment by iamdharmesh** [comment]
Hi @nikitasinelnikov, 

This is a strange issue. Can you please make sure that the TOKEN created by you has enough access to push code to the repo? 

Thanks.

**Comment by odil-io** [comment]
> Let me know if you have thoughts or ideas on how to fix that,

For as far I can tell, it seems that your token does not have enough rights as everything else is correct.

Also, [`GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) is a standard variable built for this purpose. I see you've made you own token and I'm nearly sure that is where your problem lies in this case.

In short:

In [translations.yml#L20](https://github.com/ultimatemember/recaptcha/blob/664375d13765ad6331962a985f63cd0ea5279e81/.github/workflows/translations.yml#L20) change:
```yml
GITHUB_TOKEN: ${{ secrets.GH_POT }}
```
To
```yml
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
And that should fix your problem. If not checkout the GitHub Docs linked above.
